name: Test Checkout action

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  just-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout rg-level files only'
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: platform/rg-level/
          sparse-checkout-cone-mode: false

      - name: 'Display directory content'
        shell: bash
        run: |
          pwd
          ls -l
          cd platform/rg-level
          pwd
          ls -l

      - name: 'where is my bicep file'
        shell: bash
        run: |
          cat platform/rg-level/main.bicep